# Generated by Django 4.2.7 on 2023-11-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="usuario",
            fields=[
                (
                    "run",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("correo", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                ("tipo", models.IntegerField()),
            ],
        ),
    ]
