# Generated by Django 4.2.7 on 2023-12-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cidere', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaProvRevisado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina_ant', models.IntegerField()),
                ('boton_contacto', models.IntegerField()),
            ],
            options={
                'db_table': 'tabla_prov_revisado',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CidereRegistro',
        ),
        migrations.DeleteModel(
            name='CidereUsuario',
        ),
        migrations.AlterModelTable(
            name='tablarcrud',
            table='tabla_r_crud',
        ),
    ]
