version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
      - ./django_project:/app
    env_file:
      - env
    build:
      context: .
    networks:
      - internal
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "8080:80"
    depends_on:
      - django_gunicorn
    networks:
      - internal

networks:
  internal:
    name: internal

volumes:
  static:

