# Generated by Django 3.2.3 on 2023-10-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaturas',
            name='alumnos',
            field=models.ManyToManyField(blank=True, null=True, to='course_management.Alumnos'),
        ),
    ]
