# Generated by Django 4.2.7 on 2023-11-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CidereRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(db_column='Accion', max_length=100)),
                ('id_usuario', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'cidere_registro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CidereUsuario',
            fields=[
                ('run', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.IntegerField()),
            ],
            options={
                'db_table': 'cidere_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Relleno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(db_column='Id_usuario')),
                ('region', models.CharField(max_length=50)),
                ('nombre_empresa', models.CharField(db_column='Nombre_Empresa', max_length=100)),
            ],
            options={
                'db_table': 'relleno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaAcciones',
            fields=[
                ('id_accion', models.IntegerField(primary_key=True, serialize=False)),
                ('detalle_accion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tabla_acciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaPaginas',
            fields=[
                ('id_pagina', models.IntegerField(primary_key=True, serialize=False)),
                ('pagina', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tabla_paginas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaPagRevisado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boton_contacto', models.IntegerField()),
            ],
            options={
                'db_table': 'tabla_pag_revisado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaRBusquedas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminos_busqueda', models.CharField(max_length=100)),
                ('categoria', models.IntegerField()),
                ('rubro', models.IntegerField()),
                ('tamano', models.IntegerField()),
                ('region', models.IntegerField()),
                ('provincia', models.IntegerField()),
                ('comunas', models.IntegerField()),
            ],
            options={
                'db_table': 'tabla_r_busquedas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaRCrud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tabla r_crud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaRTransacciones',
            fields=[
                ('id_transaccion', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'tabla_r_transacciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaUsuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tabla_usuario',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='asignaturas',
            name='alumnos',
        ),
        migrations.DeleteModel(
            name='Alumnos',
        ),
        migrations.DeleteModel(
            name='Asignaturas',
        ),
    ]
